init:
- git clone https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
version: 2.5.{build}
platform:
- x86
configuration:
- Release
os: Visual Studio 2015
skip_tags: true
clone_folder: C:\projects\FlashDevelop-plugins\External\Plugins\QuickNavigate
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
matrix:
  fast_finish: true
before_build:
- cd C:\projects\FlashDevelop-plugins\External\Plugins
- mv QuickNavigate C:\projects\FlashDevelop\External\Plugins
build:
  project: C:\projects\FlashDevelop\External\Plugins\QuickNavigate\FD-QuickNavigate.sln
after_build:
- mkdir $(BaseDir)
- cd $(BaseDir)
- mkdir Plugins
- cd Plugins
- mv C:\projects\FlashDevelop\External\Plugins\QuickNavigate\QuickNavigate\Bin\Release\QuickNavigate.dll QuickNavigate.dll
- cd ..\..
- 7z a QuickNavigate.zip $(BaseDir)\
- rmdir $(BaseDir) /S /Q
- mv QuickNavigate.zip %APPVEYOR_BUILD_FOLDER%\QuickNavigate.fdz
- dir
- ls
artifacts:
  - path: QuickNavigate.fdz
    name: QuickNavigate
    type: zip
deploy:
- provider: GitHub
  release: QuickNavigate-2.5.$(appveyor_build_version)
  auth_token:
    secure: HK9ej9WVysHQHeTEQ/QTOJmh08xCtDQyDBy5uXWrWV/xROMNkQrTeQv1j2tYOxVw
  artifact: /.*\.fdz/
  on:
    branch: master
