environment:
  PLUGIN_VERSION: 2.7
  PLUGIN_NAME: QuickNavigate
  PLUGIN_DESC: Quickly navigate through Types, Fields, Projects and more
  PLUGIN_PATH: C:\projects\FlashDevelop\External\Plugins\QuickNavigate
  PLUGIN_INFO: http:\/\/www.flashdevelop.org\/community\/viewtopic.php?f=4&t=5961
  PLUGIN_GITHUB_RELEASES: https:\/\/github.com\/SlavaRa\/fdplugin-quicknavigate\/releases
  APPMAN_TEMPLATE: appman.template
init:
- git clone -q https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
version: $(PLUGIN_VERSION).{build}
platform:
- x86
configuration:
- Release
os: Visual Studio 2015
skip_tags: true
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
matrix:
  fast_finish: true
before_build:
- cd ..
- mv %APPVEYOR_BUILD_FOLDER% %PLUGIN_PATH%
- nuget restore %PLUGIN_PATH%\%PLUGIN_NAME%.sln
build:
  project: $(PLUGIN_PATH)\$(PLUGIN_NAME).sln
after_build:
- mkdir %APPVEYOR_BUILD_FOLDER%\$(BaseDir)\Plugins
- mv C:\projects\FlashDevelop\FlashDevelop\Bin\Release\Plugins\%PLUGIN_NAME%.dll %APPVEYOR_BUILD_FOLDER%\$(BaseDir)\Plugins\%PLUGIN_NAME%.dll
- cd %APPVEYOR_BUILD_FOLDER%
- 7z a %PLUGIN_NAME%.zip $(BaseDir)\
- mv %PLUGIN_NAME%.zip %PLUGIN_NAME%.fdz
- cd %PLUGIN_PATH%
- mv %APPMAN_TEMPLATE% appmanconfig.txt
- cat appmanconfig.txt
- sed -i -e s/_ID_/quicknavigate/g appmanconfig.txt
- sed -i -e "s/_NAME_/%PLUGIN_NAME%/g" appmanconfig.txt
- sed -i -e "s/_DESC_/%PLUGIN_DESC%/g" appmanconfig.txt
- sed -i -e "s/_VERSION_/%PLUGIN_VERSION%/g" appmanconfig.txt
- sed -i -e "s/_BUILD_/%APPVEYOR_BUILD_NUMBER%/g" appmanconfig.txt
- sed -i -e "s/_INFO_/%PLUGIN_INFO%/g" appmanconfig.txt
- sed -i -e "s/_URL_/%PLUGIN_GITHUB_RELEASES%\/download\/%APPVEYOR_BUILD_VERSION%\/%PLUGIN_NAME%.fdz/g" appmanconfig.txt
- md5sum %APPVEYOR_BUILD_FOLDER%\%PLUGIN_NAME%.fdz > checksum.md5
- sed 's/ \*.*//' checksum.md5
- cat checksum.md5
- set /p CHECKSUM=<checksum.md5
- sed -i -e "s/_CHECKSUM_/%CHECKSUM%/g" appmanconfig.txt
- cat appmanconfig.txt
artifacts:
- path: $(PLUGIN_NAME).fdz
  name: $(PLUGIN_NAME)
  type: zip
- path: appmanconfig.txt
  name: appmanconfig
  type: txt
deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  auth_token:
    secure: HK9ej9WVysHQHeTEQ/QTOJmh08xCtDQyDBy5uXWrWV/xROMNkQrTeQv1j2tYOxVw
  artifact: /(.*\.fdz)|(appmanconfig.txt)/
  on:
    branch: master
