init:
- git clone https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
version: 2.5.{build}
platform:
- x86
configuration:
- Release
os: Visual Studio 2015
skip_tags: true
environment:
  PLUGIN_NAME: QuickNavigate
clone_folder: C:\projects\FlashDevelop-plugins\External\Plugins\%PLUGIN_NAME%
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
matrix:
  fast_finish: true
before_build:
- cd C:\projects\FlashDevelop-plugins\External\Plugins
- mv %PLUGIN_NAME% C:\projects\FlashDevelop\External\Plugins
build:
  project: C:\projects\FlashDevelop\External\Plugins\$(PLUGIN_NAME)\FD-QuickNavigate.sln
after_build:
- mkdir %PLUGIN_NAME%\$(BaseDir)\Plugins && cd %PLUGIN_NAME%\$(BaseDir)\Plugins
- mv C:\projects\FlashDevelop\FlashDevelop\Bin\Release\Plugins\%PLUGIN_NAME%.dll %PLUGIN_NAME%.dll
- cd ..\..
- 7z a %PLUGIN_NAME%.fdz $(BaseDir)\
artifacts:
  - path: $(PLUGIN_NAME).fdz
    name: $(PLUGIN_NAME)
    type: zip
deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  auth_token:
    secure: HK9ej9WVysHQHeTEQ/QTOJmh08xCtDQyDBy5uXWrWV/xROMNkQrTeQv1j2tYOxVw
  artifact: /.*\.fdz/
  on:
    branch: master
