init:
- git clone https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
version: 2.5.{build}
platform:
- x86
configuration:
- Release
os: Visual Studio 2015
skip_tags: true
environment:
  PluginName: QuickNavigate
clone_folder: C:\projects\FlashDevelop-plugins\External\Plugins\%PluginName%
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
matrix:
  fast_finish: true
before_build:
- cd C:\projects\FlashDevelop-plugins\External\Plugins
- mv %PluginName% C:\projects\FlashDevelop\External\Plugins
build:
  project: C:\projects\FlashDevelop\External\Plugins\%PluginName%\FD-QuickNavigate.sln
after_build:
- mkdir %PluginName%\$(BaseDir)\Plugins && cd %PluginName%\$(BaseDir)\Plugins
- mv C:\projects\FlashDevelop\FlashDevelop\Bin\Release\Plugins\%PluginName%.dll %PluginName%.dll
- cd ..\..
- 7z a %PluginName%.fdz $(BaseDir)\
artifacts:
  - path: %PluginName%.fdz
    name: %PluginName%
    type: zip
deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  auth_token:
    secure: HK9ej9WVysHQHeTEQ/QTOJmh08xCtDQyDBy5uXWrWV/xROMNkQrTeQv1j2tYOxVw
  artifact: /.*\.fdz/
  on:
    branch: master
