init:
- git clone https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
os: Visual Studio 2015
version: '{build}'
skip_tags: true
clone_depth: 10
clone_folder: C:\projects\FlashDevelop-plugins\External\QuickNavigate
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
platform:
- x86
configuration:
- Debug
- Release
matrix:
  fast_finish: true
before_build:
- cd C:\projects\FlashDevelop-plugins\External
- mv QuickNavigate C:\projects\FlashDevelop\External
- cd C:\projects\FlashDevelop\External\QuickNavigate
build:
- msbuild FD-QuickNavigate.sln