init:
- git clone https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
os: Visual Studio 2015
version: '{build}'
skip_tags: true
clone_depth: 10
clone_folder: C:\projects\FlashDevelop-plugins\External\Plugins\QuickNavigate
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
platform:
- x86
configuration:
- Debug
- Release
matrix:
  fast_finish: true
before_build:
- cd C:\projects\FlashDevelop-plugins\External\Plugins
- mv QuickNavigate C:\projects\FlashDevelop\External\Plugins
build:
  project: C:\projects\FlashDevelop\External\Plugins\QuickNavigate\FD-QuickNavigate.sln
deploy:
- provider: GitHub
  release: QuickNavigate-2.5.$(appveyor_build_version)
  auth_token:
    secure: HK9ej9WVysHQHeTEQ/QTOJmh08xCtDQyDBy5uXWrWV/xROMNkQrTeQv1j2tYOxVw
  artifact: /.*\QuickNavigate.dll/
  draft: false
  prerelease: false
  on:
    branch: master
    configuration: release
